### ISSUE TITLE
worker with func exits from a panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by z3dc0ps** [jaeles-project/jaeles#33]
![1](https://user-images.githubusercontent.com/61974788/98460920-7384e180-21ce-11eb-96cb-c438af9b1c5b.PNG)

**Comment by z3dc0ps** [comment]
![1](https://user-images.githubusercontent.com/61974788/98460961-b941aa00-21ce-11eb-8fd2-ca15d41edbb2.PNG)

**Comment by j3ssie** [comment]
It should be fixed now with the latest signature.
Just delete `~/.jaeles`  then run `jaeles config init` to update

**Comment by z3dc0ps** [comment]
still getting error
![1](https://user-images.githubusercontent.com/61974788/99097214-53558800-25fd-11eb-92a8-2f9018d142bf.PNG)
